const UPDATE_POST = "UPDATE_POST";
const CREATE_POST = "CREATE_POST";
const DELETE_POST = "DELETE_POST";
const POST_DETAILS = "POST_DETAILS";
export { UPDATE_POST, CREATE_POST, DELETE_POST, POST_DETAILS };
