const GET_USERS = "GET_USERS";
const UPDATE_USER = "UPDATE_USER";
const GET_USER_BY_ID = "GET_USER_BY_ID";
const DELETE_USER = "DELETE_USER";
const SAVE_POST = "SAVE_USER";
const USER_PROFILE = "USER_PROFILE";
const USER_NOTIFIACTION = "USER_NOTIFIACTION";
export {
  GET_USERS,
  UPDATE_USER,
  GET_USER_BY_ID,
  DELETE_USER,
  SAVE_POST,
  USER_PROFILE,
  USER_NOTIFIACTION,
};
